/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'userId' : Principal,
  'timestamp' : Time,
  'details' : string,
  'eventType' : string,
}
export interface AdminPreference {
  'value' : boolean,
  'preferenceType' : string,
}
export interface FileMeta {
  'contentType' : string,
  'size' : bigint,
  'filename' : string,
  'fileId' : string,
  'uploadTime' : Time,
}
export interface JourneyInteraction {
  'interactionType' : string,
  'isCorrect' : boolean,
  'response' : string,
  'timestamp' : Time,
  'questionId' : bigint,
  'interactionId' : bigint,
}
export interface JourneySession {
  'user' : Principal,
  'state' : string,
  'sessionId' : bigint,
}
export type Time = bigint;
export interface TrackedFileEvent {
  'additionalData' : string,
  'fileMeta' : FileMeta,
  'uploadTimestamp' : Time,
  'eventType' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJourneySession' : ActorMethod<[Principal, string], bigint>,
  'deleteLocalFile' : ActorMethod<[string], boolean>,
  'fileUploaded' : ActorMethod<[TrackedFileEvent], boolean>,
  'getActivitiesByType' : ActorMethod<
    [Principal, string],
    Array<ActivityEvent>
  >,
  'getAllActivities' : ActorMethod<[], Array<ActivityEvent>>,
  'getAllFileUploads' : ActorMethod<[], Array<FileMeta>>,
  'getAllLocalFiles' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInProgressJourneys' : ActorMethod<[], Array<{}>>,
  'getJourneyByStatus' : ActorMethod<[string], Array<{}>>,
  'getJourneySection' : ActorMethod<[string], Array<JourneyInteraction>>,
  'getJourneySessionsForUser' : ActorMethod<[Principal], Array<JourneySession>>,
  'getUserActivities' : ActorMethod<[Principal], Array<ActivityEvent>>,
  'getUserPreferences' : ActorMethod<[], Array<AdminPreference>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordActivity' : ActorMethod<[ActivityEvent], undefined>,
  'recordActivityEvent' : ActorMethod<[{}], undefined>,
  'requestDataExport' : ActorMethod<
    [{}],
    { 'status' : { 'queued' : null }, 'message' : string, 'timestamp' : Time }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJourneyResponse' : ActorMethod<[{ 'answerId' : bigint }], bigint>,
  'sendNotification' : ActorMethod<[Principal, string, string], boolean>,
  'setUserPreference' : ActorMethod<[AdminPreference], undefined>,
  'updateExportStatus' : ActorMethod<[string, {}], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];