/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FileMeta = IDL.Record({
  'contentType' : IDL.Text,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
  'fileId' : IDL.Text,
  'uploadTime' : Time,
});
export const TrackedFileEvent = IDL.Record({
  'additionalData' : IDL.Text,
  'fileMeta' : FileMeta,
  'uploadTimestamp' : Time,
  'eventType' : IDL.Text,
});
export const ActivityEvent = IDL.Record({
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const JourneyInteraction = IDL.Record({
  'interactionType' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'response' : IDL.Text,
  'timestamp' : Time,
  'questionId' : IDL.Nat,
  'interactionId' : IDL.Nat,
});
export const JourneySession = IDL.Record({
  'user' : IDL.Principal,
  'state' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const AdminPreference = IDL.Record({
  'value' : IDL.Bool,
  'preferenceType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJourneySession' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'deleteLocalFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'fileUploaded' : IDL.Func([TrackedFileEvent], [IDL.Bool], []),
  'getActivitiesByType' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getAllActivities' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getAllFileUploads' : IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
  'getAllLocalFiles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInProgressJourneys' : IDL.Func([], [IDL.Vec(IDL.Record({}))], ['query']),
  'getJourneyByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({}))],
      ['query'],
    ),
  'getJourneySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JourneyInteraction)],
      ['query'],
    ),
  'getJourneySessionsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JourneySession)],
      ['query'],
    ),
  'getUserActivities' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getUserPreferences' : IDL.Func([], [IDL.Vec(AdminPreference)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordActivity' : IDL.Func([ActivityEvent], [], []),
  'recordActivityEvent' : IDL.Func([IDL.Record({})], [], []),
  'requestDataExport' : IDL.Func(
      [IDL.Record({})],
      [
        IDL.Record({
          'status' : IDL.Variant({ 'queued' : IDL.Null }),
          'message' : IDL.Text,
          'timestamp' : Time,
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJourneyResponse' : IDL.Func(
      [IDL.Record({ 'answerId' : IDL.Nat })],
      [IDL.Nat],
      [],
    ),
  'sendNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setUserPreference' : IDL.Func([AdminPreference], [], []),
  'updateExportStatus' : IDL.Func([IDL.Text, IDL.Record({})], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FileMeta = IDL.Record({
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
    'fileId' : IDL.Text,
    'uploadTime' : Time,
  });
  const TrackedFileEvent = IDL.Record({
    'additionalData' : IDL.Text,
    'fileMeta' : FileMeta,
    'uploadTimestamp' : Time,
    'eventType' : IDL.Text,
  });
  const ActivityEvent = IDL.Record({
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const JourneyInteraction = IDL.Record({
    'interactionType' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'response' : IDL.Text,
    'timestamp' : Time,
    'questionId' : IDL.Nat,
    'interactionId' : IDL.Nat,
  });
  const JourneySession = IDL.Record({
    'user' : IDL.Principal,
    'state' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const AdminPreference = IDL.Record({
    'value' : IDL.Bool,
    'preferenceType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJourneySession' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'deleteLocalFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'fileUploaded' : IDL.Func([TrackedFileEvent], [IDL.Bool], []),
    'getActivitiesByType' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getAllActivities' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getAllFileUploads' : IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
    'getAllLocalFiles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInProgressJourneys' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({}))],
        ['query'],
      ),
    'getJourneyByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Record({}))],
        ['query'],
      ),
    'getJourneySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JourneyInteraction)],
        ['query'],
      ),
    'getJourneySessionsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JourneySession)],
        ['query'],
      ),
    'getUserActivities' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getUserPreferences' : IDL.Func([], [IDL.Vec(AdminPreference)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordActivity' : IDL.Func([ActivityEvent], [], []),
    'recordActivityEvent' : IDL.Func([IDL.Record({})], [], []),
    'requestDataExport' : IDL.Func(
        [IDL.Record({})],
        [
          IDL.Record({
            'status' : IDL.Variant({ 'queued' : IDL.Null }),
            'message' : IDL.Text,
            'timestamp' : Time,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJourneyResponse' : IDL.Func(
        [IDL.Record({ 'answerId' : IDL.Nat })],
        [IDL.Nat],
        [],
      ),
    'sendNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setUserPreference' : IDL.Func([AdminPreference], [], []),
    'updateExportStatus' : IDL.Func([IDL.Text, IDL.Record({})], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };